# Generated by Django 3.0.7 on 2020-09-20 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mediafinder', '0002_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='favorites',
            new_name='favourites',
        ),
        migrations.AddField(
            model_name='search',
            name='result_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
